In [1]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [ ]:
# -*- coding: utf-8 -*-
import numpy as np
import math

# Create random input and output data
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

# Randomly initialize weights
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6

for t in range(20000):
    # Forward pass: compute predicted y
    # y = a + b x + c x^2 + d x^3
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = math.sqrt(np.square(y_pred - y).sum())
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

In [8]:
import torch
import math

device = "cuda:0" if torch.cuda.is_available() else "cpu"

device = torch.device(device)

X = torch.linspace(-math.pi,math.pi,2000, device=device, dtype=torch.float)
y = torch.sin(X)




In [15]:
a = torch.randn((1,),device=device, dtype=torch.float)


In [16]:
a

tensor([-0.4288])

In [17]:
a.device

device(type='cpu')

In [18]:
a.layout

torch.strided

In [19]:
a.data

tensor([-0.4288])

In [21]:
a.dtype

torch.float32

In [23]:
a.grad_fn

TypeError: ignored

In [24]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
y.backward(torch.ones(2, 2), retain_graph=True)
# the retain_variables flag will prevent the internal buffers from being freed
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [28]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
y.backward()
# the retain_variables flag will prevent the internal buffers from being freed
print(x.grad)

RuntimeError: ignored

In [27]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)