# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


## 1. Installation Instructions
    
    conda install numpy
    

### Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We will focus on some of the most important aspects of Numpy: vectors, arrays, matrices, and number generation.

## 2. Numpy Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 


Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

### 2.1. Creating NumPy Arrays from Python List


We can create an array by directly converting a list or list of lists:

In [5]:
# Casting
my_list = [1,2,3]
my_list_ar = np.array(my_list)
my_list_ar

array([1, 2, 3])

In [6]:
my_list_ar.astype(float)

array([1., 2., 3.])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

### 2.2. Generating arrays from bulid-in functions

There are lots of built-in ways to generate Arrays: 
- **arange** : Return evenly spaced values within a given interval.
- **linspace** : Return evenly spaced numbers over a specified interval (prefered to arange).
- **zeros** : Return a new array of given shape and type, filled with zeros.
- **zeros_like** : Return an array of zeros with the same shape and type as a given array.
- **ones** : Return a new array setting values to one.
- **fill** : Return a new array of given shape filled with value (array exists aleardy).
- **full** : Creates an array of the given shape initialized with the given value (new one). 
- **empty** : Return a new array of given shape and type, without initializing entries. its content is not predictable. `empty`, unlike `zeros`, does not set the array values to zero,
and may therefore be marginally faster.  On the other hand, it requires
the user to manually set all the values in the array, and should be
used with caution.
- **eyes** : Return a 2-D array with ones on the diagonal and zeros elsewhere.
- **identity** : (almost) equivalent function to **eyes**
- **diag** : diagonal 2-D array from a 1-D array specified by the user.

In [1]:
import numpy as np
help (np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [9]:
np.linspace(0,10,50, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [10]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

### 2.3. Performance measurement
The key advantages of numpy are convenience and speed of computation.

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [12]:
c = range(10000)
%timeit [i**3 for i in c]

4.44 ms ± 462 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
c_numpy = np.arange(10000)
t =%timeit -o c_numpy**3 
print(t)

32.1 µs ± 1.72 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
32.1 µs ± 1.72 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [19]:
%timeit?

Docstring:
Time execution of a Python statement or expression

Usage, in line mode:
  %timeit [-n<N> -r<R> [-t|-c] -q -p<P> -o] statement
or in cell mode:
  %%timeit [-n<N> -r<R> [-t|-c] -q -p<P> -o] setup_code
  code
  code...

Time execution of a Python statement or expression using the timeit
module.  This function can be used both as a line and cell magic:

- In line mode you can time a single-line statement (though multiple
  ones can be chained with using semicolons).

- In cell mode, the statement in the first line is used as setup code
  (executed but not timed) and the body of the cell is timed.  The cell
  body has access to any variables created in the setup code.

Options:
-n<N>: execute the given statement <N> times in a loop. If <N> is not
provided, <N> is determined so as to get sufficient accuracy.

-r<R>: number of repeats <R>, each consisting of <N> loops, and take the
best result.
Default: 7

-t: use time.time to measure the time, which is the default on Unix.
This f

More details will given in section `"Broadcasting and Vectorization"`.

### 2.4. Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

In [11]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
a.shape

(3, 4)

In [ ]:
a.ndim  # equal to len(a.shape)

In [ ]:
a.size

### 2.5. Array attributes and methods 

#### 2.5.1. `dtype`
NumPy's `ndarray`s are also efficient in part because all their elements must have the same type (usually numbers).
You can check what the data type is by looking at the `dtype` attribute:

In [ ]:
### dtype: You can also grab the data type of the object in the array
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

print(arr.dtype, arr)

In [ ]:
arr = np.arange(0, 25.0)
print(arr.dtype, arr)

#### 2.5.2. `Reshape`
Changing the shape of an `ndarray` is as simple as setting its `shape` attribute. However, the array's size must remain the same (in place).

In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[21 30  3 34 45 28 43  1 36 43]


In [23]:
c = arr.reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
c[0] = 10 #changing some values

In [25]:
c

array([[10, 10, 10, 10, 10],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr #is also modified (a view)

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### 2.5.5. `ravel`
Finally, the `ravel` function returns a new one-dimensional `ndarray` that also points to the same data:

In [27]:
d = c.ravel()

In [28]:
d.shape

(25,)

In [29]:
d.ndim

1

In [30]:
d

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

`c and d` have different memory addresses but the are viewing the same data in memory: !!!!

In [31]:
c[0] = 99
c

array([[99, 99, 99, 99, 99],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
d

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### 2.5.6. `max, min, argmax, argmin`

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [33]:
ranarr

array([21, 30,  3, 34, 45, 28, 43,  1, 36, 43])

In [36]:
c

array([[99, 99, 99, 99, 99],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
def test(a,b)->int:
    '''
    a is the max 
    b is the min
    '''
    return a+b
    

In [42]:
ranarr.max()

45

In [43]:
ranarr.argmax()

4

In [44]:
ranarr.min()

1

In [45]:
ranarr.argmin()

7

In [ ]:
print(c)
c.max(axis=1)